name: FastAPI - Basic Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Instalar Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Instalar depedencias
        run: poetry install --no-interaction --no-root

      - name: Rodar Testes
        run: poetry run pytest -v

  docker-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build imagem
        run: docker build -t fastapi-app:latest .

      - name: Run Dockerfile
        run: docker run -d -p 8080:8080 --name container-teste fastapi-app:latest
      
