name: FastAPI - Basic Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Instalar Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Instalar depedencias
        run: poetry install --no-interaction --no-root

      - name: Rodar Testes
        run: poetry run pytest -v

  docker-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build imagem
        run: docker build -t fastapi-app:latest .

      - name: Run Dockerfile
        run: docker run -d -p 8080:8080 --name container-teste fastapi-app:latest

      - name: Simular inicialização do container (Smoke Test)
        run: |
          # 1. Remove o contêiner antigo se ele existir (o '|| true' impede a pipeline de quebrar se não existir)
          docker rm -f container-teste || true
          
          # 2. Agora o caminho está livre para rodar o novo contêiner com segurança
          docker run -d -p 8080:8080 --name container-teste fastapi-app:latest
          
          # 3. Aguarda a inicialização
          sleep 5
          
          # 4. Valida se continua de pé
          docker ps | grep container-teste | grep Up
      
      - name: Validar se a API responde (Healthcheck)
        run: |
          # 4. Faz uma requisição HTTP na rota principal ou de docs para ver se a API responde com sucesso (Status 200)
          curl --fail http://localhost:8080/docs || exit 1

      - name: Limpar o container de teste
        if: always() # Garante que o container será parado mesmo se os passos anteriores falharem
        run: docker rm -f container-teste
      
